[dr]
type = drive
scope = drive
token: {"access_token":"ya29.a0Aa7MYioGcvFe3Ubbz66CgVR-LbURgjxWcGciwdQtLMSRuCtVs_RWjpgyxx3u6cBkQ3OS30gjIeK3ZAihEjKtHkYdjo7fOI4pGGPM0aIfvdMEmJfGHd4ElmbLmCAywxSIl7s85w6DDhmlT2YdnthMRVUxsxnONT-kITLXWPA5G88vCW_F2SgAJ2NHOckGF2dl6Aarda4aCgYKAW0SARASFQHGX2MiXB7LKH8NK7gAFizRcyCcDg0206","token_type":"Bearer","refresh_token":"1//0gpFAJZwsWd3pCgYIARAAGBASNgF-L9IrbQfvSDoRx5C8s5q5MS5NqgCosPwJz7C_C2RirJYKnDdRo3v2nZcmvd2MfwBpM6r7mg","expiry":"2026-03-24T05:59:16.0905643+07:00","expires_in":3599}
